### PR TITLE
1.31 Add tabbed ViewPager in MainActivity to swipe between 4 lists of words

### PR DESCRIPTION
**Pull request by danielmai**
Addresses #5.

- Add the design support library dependency for TabLayout
- Remove the 4 category activities
- Modify activity_main.xml with view pager and tab layout
- Add a CategoryAdapter (FragmentPagerAdapter) class for view pager

---

From #5:

> Order for the fragments should be:
Numbers is the leftmost fragment, followed by family fragment, then colors fragment, then phrases fragment.

Done

> Make sure rotation of the screen works (should stay on the same page of the ViewPager).

Done. The fragment states are preserved across rotations with the fragment manager in the FragmentPagerAdapter.

---

I created the CategoryAdapter implementation based of [Chris Banes's implementation in cheesesquare](https://github.com/chrisbanes/cheesesquare/blob/master/app/src/main/java/com/support/android/designlibdemo/MainActivity.java#L123-L150).

---

**Aside: Performance**
Also, the performance of the category lists with images (Numbers, Family, and Colors) is janky because loading the different images causes GC events. Tapping on the tabs across those three fragments makes the jank obvious compared to the smoother transition going from Color to Phrases (because Phrases doesn't have to load any images).

Looking at the memory monitor while paging between tabs shows that memory is constantly being GC'd. **This was also happening in the previous implementation with separate category activities**. Is this something significant enough to address?

### CODE REVIEW

**Comment by kkuan2011** [comment]
Hmm good catch on the performance problem. If you use the Glide library to load in the images (like in Chris' cheesesquare app), does that fix the jank and reduce memory usage? (Should just be adding in the library in the gradle file and a Glide library method call when we set the image on the imageview)

**Comment by danielmai** [comment]
> If you use the Glide library to load in the images (like in Chris' cheesesquare app), does that fix the jank and reduce memory usage? (Should just be adding in the library in the gradle file and a Glide library method call when we set the image on the imageview)

That definitely does the trick. Memory usage is even lower than the original implementation and  again. :+1: 

**(Before Glide)** Memory usage after initially starting the app:

screen shot 2016-02-17 at 10 21 29 pm

**(After Glide)** Memory usage after initially starting the app:
screen shot 2016-02-17 at 10 24 56 pm

**Comment by danielmai** [comment]
Added new commits @kkuan2011

**Comment by kkuan2011** [comment]
Hi Daniel! Did you want to resolve the conflicts in this branch? Or should I review as is?

**Comment by danielmai** [comment]
I'll resolve the conflicts today and then you can review it.

**Comment by danielmai** [comment]
OK, it's ready for review.

**Pull request merged**
